Time::DATE_FORMATS[:default] = '%Y年%m月%d日 %H:%M'
Time::DATE_FORMATS[:datetime] = '%Y年%m月%d日 %H:%M'
Time::DATE_FORMATS[:date] = '%Y年%m月%d日'
Time::DATE_FORMATS[:time] = '%H:%M:%S'
Date::DATE_FORMATS[:default] = '%Y年%m月%d日'
